### PR TITLE
Pipenv

### PR DESCRIPTION
**Pull request by veenhouse**

### CODE REVIEW

**Review by kennethmorton — COMMENTED** [review]
There are a lot of activities going on in this. I would rather see each intent separated out into an individual PR.

**Comment by RichardBruskiewich** [comment]
Hello Luke @veenhouse (@yakaboskic @sierra-moxon @kennethmorton), 

I see that Kenny has responded to this PR. I concur with his general conclusion. 

Given the large number of files which are touched (some of which may now be somewhat out-of-sync with the latest *master* branch code), it is mildly challenging to understand:  is this PR mainly a reconfiguration of the project as a **pipenv** managed project, or are there library specific code changes that are proposed? I suspect mostly the former; very little (maybe none?) of the latter? Please kindly point out where this is not the case.  

BTW, release 2.2.7 of the package is more flexible in handling TRAPI versions... We could double check if this fixes concerns of one of commit [e3afa13](https://github.com/NCATSTranslator/reasoner-validator/pull/21/commits/e3afa133b92f5806b98209a53dffb772bdad218e) above?

@sierra-moxon is also suggesting that if we feel a strong compulsion to upgrade the dependency/deployment management subsystem of the project, that we perhaps consider Poetry, as opposed to Pipenv as the implementation.

I'll tag this PR as 'draft' pending some further consideration of the above concerns, ok?

**Comment by RichardBruskiewich** [comment]
@veenhouse (cc: @kennethmorton, @sierra-moxon, @edeutsch ) since this PR originated 16 months ago, and the *master* branch has changed somewhat since there, perhaps you need to merge master into your branch, reconcile the conflicts, while confirming that the software still works as expected.

Once again, there is also the suggestion that `poetry` be substituted in lieu of `pipenv`. If most of this PR relates just to pipenv, then perhaps we need to have a more compelling case for retaining (and merging) the PR: what use case are we solving here?

**Comment by RichardBruskiewich** [comment]
PR https://github.com/NCATSTranslator/reasoner-validator/pull/51 has converted the **reasoner-validator** project to use the **poetry** dependency management system, thus this PR is considered obsolete.

**Pull request closed without merging**
